apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginxApp.fullname" . }}-env
  labels:
    {{- include "nginxApp.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
data:
  index.html: |
    {{ .Values.content | nindent 4 }}
